# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/jaksi/sshesame:v0.0.25"
  amd64: "ghcr.io/jaksi/sshesame:v0.0.25"
  armv7: "ghcr.io/jaksi/sshesame:v0.0.25"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: sshesame add-on"
  org.opencontainers.image.description: "An easy to set up and use SSH honeypot, a fake SSH server that lets anyone in and logs their activity"
  org.opencontainers.image.source: "https://github.com/tolkonepiu/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
