# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Python executor add-on
version: "0.0.1"
slug: python_exec
description: Simple python executor for Home Assistant
url: "https://github.com/tolkonepiu/ha-addons/tree/main/python_exec"
image: "ghcr.io/tolkonepiu/{arch}-addon-python_exec"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
init: false
audio: true
video: true
gpio: true
uart: true
udev: true
devices:
  - i2c-0
  - i2c-1
  - i2c-10
  - i2c-22
  - /dev/spidev0.0
  - /dev/mem
privileged:
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
options:
  code: |
    print('Hello, world!')
  requirements: []
schema:
  code: str
  requirements:
    - str
